# Generated by Django 5.0.6 on 2025-08-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_producerproductaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members_can_see_other_members',
            field=models.BooleanField(default=True),
        ),
    ]
