services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certificates:/etc/letsencrypt:ro
      - ./nginx/html:/usr/share/nginx/html
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certificates:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html -d royaltyx.co -d www.royaltyx.co -d api.royaltyx.co -d app.royaltyx.co -d flower.royaltyx.co --email nenadblagovcanin2@gmail.com --agree-tos --no-eff-email --non-interactive
