services:

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 15s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes:
      - "./backend:/backend"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build:
       context: ./frontend
       dockerfile: Dockerfile.local
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    command: npm run start
    env_file:
      - .env

volumes:
  postgres_data:
  