# Generated by Django 5.0.6 on 2025-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0009_alter_source_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("paused", "Paused")],
                default="active",
                max_length=20,
            ),
        ),
    ]
