# Generated by Django 5.0.6 on 2025-07-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_productuser_model'),
        ('product', '0018_alter_product_thumbnail'),
    ]

    operations = [
    ]
