# Generated by Django 5.0.6 on 2025-07-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_verification_token_expiry'),
        ('user', '0008_user_grace_period_end_user_payment_failure_count_and_more'),
    ]

    operations = [
    ]
