name: Backend Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rename .env.test to .env
        run: mv .env.test .env

      - name: Set up Docker Compose
        run: docker compose -f local.yml up -d

      - name: Wait for backend service to be ready
        run: |
          echo "Waiting for backend service to be ready..."
          for i in {1..30}; do
            if docker compose -f local.yml exec backend python manage.py showmigrations &> /dev/null; then
              echo "Backend is ready."
              break
            fi
            echo "Waiting... ($i)"
            sleep 2
          done

      - name: Run Django tests in backend container
        run: docker compose -f local.yml exec backend python manage.py test apps

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f local.yml down
