name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH for server access (Optional, if your server requires SSH for git pull)
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: SSH into the server and run deployment commands
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}  # Define your server's IP address/hostname
          username: ${{ secrets.SERVER_USERNAME }}  # Define your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key from GitHub Secrets
          script: |
            cd RoyaltyX/
            git pull origin main
            docker-compose -f production.yml up -d --build
