name: E2E Tests

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps
      
      - name: Build frontend
        run: |
          cd frontend
          npm run build
      
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      - name: Set up environment variables
        run: |
          cp .env.example .env
      
      - name: Run backend migrations
        run: |
          cd backend
          python manage.py migrate
      
      - name: Start backend server
        run: |
          cd backend
          python manage.py runserver &
          sleep 10
      
      - name: Serve frontend build
        run: |
          cd frontend
          npx serve -s build -l 3000 &
          sleep 5
      
      - name: Wait for servers to be ready
        run: |
          npx wait-on http://localhost:3000 http://localhost:8000 --timeout 60000
      
      - name: Run Cypress tests
        run: |
          cd frontend
          npm run cypress:run:headless
      
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          retention-days: 7
      
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          retention-days: 7
